[package]
name = "nmrs-gui"
version = "1.6.0"
authors = ["Akrm Al-Hakimi <alhakimiakrmj@gmail.com>"]
edition = "2024"
rust-version = "1.85.0"
description = "GTK4 GUI for managing NetworkManager connections"
license = "MIT"
repository = "https://github.com/networkmanager-rs/nmrs-gui"
keywords = ["networkmanager", "gui", "gtk", "linux"]
categories = ["gui"]
publish = true

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
incremental = false
panic = "abort"
strip = true

[lints.rust]
unused = { level = "warn", priority = -1 }

[lints.clippy]
too_many_arguments = "allow"
type_complexity = "allow"

[dependencies]
nmrs = "3.1.5"
gtk = { version = "0.11.0", package = "gtk4" }
adw = { version = "^0.9", package = "libadwaita", features = ["v1_6", "v1_8"] }
glib = "0.22"
dirs = "6.0.0"
fs2 = "0.4.3"
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }
tokio = { version = "1.52", features = ["rt-multi-thread", "macros", "sync", "time"] }
tokio-util = "0.7.18"
log = "0.4"
